### ISSUE TITLE
Is it okay to use this course?

### ISSUE THREAD

**Issue by privefl** [dcl-2017-04/curriculum#2]
Hello,

I'm preparing some materials for an advanced R course of my city's doctoral school.
I plan a whole part on analysis with R (using the *R for Data Science* book) and I've come across this course.

Is it okay to use this course in mine? (I'm not sure about licensing and other stuff)
It would save me quite some time and would surely be better materials than I could come up with.

My course materials (in progress) are available at https://privefl.github.io/advr38book/data-analysis-with-the-tidyverse.html.

**Comment by behrman** [comment]
We designed these materials for others to use, and you should feel free to.

They are licensed under the [Creative Commons Attribution-NonCommercial 4.0 International license](https://github.com/dcl-2017-04/curriculum/blob/master/LICENSE.md).

We have [newer materials](https://dcl-2018-01.github.io/curriculum/) for course we are currently teaching. These should be complete by 2018-04.
